# Generated by Django 4.2.18 on 2026-03-23 19:06

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("tag", "0001_initial"),
        ("image", "0007_alter_image_file_alter_image_user"),
    ]

    operations = [
        migrations.CreateModel(
            name="ImageTag",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "image",
                    models.ForeignKey(
                        help_text="Imagen asociada.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_tags",
                        to="image.image",
                        verbose_name="Imagen",
                    ),
                ),
                (
                    "tag",
                    models.ForeignKey(
                        help_text="Etiqueta asociada.",
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="image_tags",
                        to="tag.tag",
                        verbose_name="Etiqueta",
                    ),
                ),
            ],
            options={
                "verbose_name": "Relacion imagen-etiqueta",
                "verbose_name_plural": "Relaciones imagen-etiqueta",
                "db_table": "image_tags",
                "indexes": [
                    models.Index(
                        fields=["image"], name="image_tags_image_i_9d4d49_idx"
                    ),
                    models.Index(fields=["tag"], name="image_tags_tag_id_9cac66_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="imagetag",
            constraint=models.UniqueConstraint(
                fields=("image", "tag"), name="uq_image_tags_image_tag"
            ),
        ),
    ]
