# Generated by Django 4.2.4 on 2023-08-16 03:23

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                default="O",
                help_text="Género del usuario.",
                max_length=1,
                verbose_name="Género",
            ),
        ),
    ]
