# Generated by Django 4.2.4 on 2023-08-16 03:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0002_alter_user_gender"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": 'Registro "Usuario"',
                "verbose_name_plural": "Tabla de registros \nusuarios\n",
            },
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="Dirección del usuario.",
                max_length=60,
                verbose_name="Dirección",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="E-mail del usuario.",
                max_length=60,
                unique=True,
                verbose_name="E-mail",
            ),
        ),
    ]
