# Generated by Django 4.2.4 on 2023-08-16 22:39

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0003_alter_user_options_alter_user_address_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": 'Registro "Usuario"',
                "verbose_name_plural": "Tabla de registros \nUsuario\n",
            },
        ),
    ]
