# Generated by Django 4.1.3 on 2023-09-02 02:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("user", "0004_alter_user_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="image",
            field=models.ImageField(
                blank=True,
                null=True,
                upload_to="usuario/avatar/",
                verbose_name="Imagen",
            ),
        ),
    ]
