# Generated by Django 5.2.3 on 2026-03-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0005_user_image"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "User record",
                "verbose_name_plural": "User records",
            },
        ),
        migrations.RemoveField(
            model_name="user",
            name="image",
        ),
        migrations.RemoveField(
            model_name="user",
            name="last_name",
        ),
        migrations.AddField(
            model_name="user",
            name="accepted_terms",
            field=models.BooleanField(
                default=False,
                help_text="Indicates whether the user accepted the terms and conditions.",
                verbose_name="Accepted terms and conditions",
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="maternal_last_name",
            field=models.CharField(
                default=2,
                help_text="User's maternal last name.",
                max_length=100,
                verbose_name="Maternal last name",
            ),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="user",
            name="paternal_last_name",
            field=models.CharField(
                default=1,
                help_text="User's paternal last name.",
                max_length=100,
                verbose_name="Paternal last name",
            ),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="user",
            name="address",
            field=models.CharField(
                blank=True,
                help_text="User address.",
                max_length=60,
                verbose_name="Address",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="email",
            field=models.EmailField(
                help_text="User email.",
                max_length=60,
                unique=True,
                verbose_name="Email",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(
                help_text="User's first name(s).",
                max_length=100,
                verbose_name="First name",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="gender",
            field=models.CharField(
                choices=[("M", "Masculino"), ("F", "Femenino"), ("O", "Otro")],
                default="O",
                help_text="User gender.",
                max_length=1,
                verbose_name="Gender",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="phone",
            field=models.CharField(blank=True, max_length=9, verbose_name="Phone"),
        ),
    ]
