# Generated by Django 5.2.3 on 2026-03-28 00:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("reward", "0006_delete_imagereward"),
    ]

    operations = [
        migrations.RenameIndex(
            model_name="rewardrule",
            new_name="reward_rule_is_acti_5c9635_idx",
            old_name="reward_rule_is_acti_idx",
        ),
        migrations.RenameIndex(
            model_name="rewardrule",
            new_name="reward_rule_score_m_a22982_idx",
            old_name="reward_rule_score_m_idx",
        ),
        migrations.RenameIndex(
            model_name="rewardwithdrawal",
            new_name="reward_with_user_id_ca3c1d_idx",
            old_name="reward_with_user_id_is_paid_idx",
        ),
    ]
