# Generated by Django 4.2.18 on 2026-03-23 17:05

import uuid

import django.utils.timezone
import model_utils.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Image",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                ("file", models.ImageField(upload_to="images/%Y/%m/%d/")),
                ("file_name", models.CharField(max_length=255)),
                ("captured_at", models.DateTimeField(blank=True, null=True)),
                ("uploaded_at", models.DateTimeField(auto_now_add=True)),
                ("ip_address", models.GenericIPAddressField(blank=True, null=True)),
                (
                    "device_type",
                    models.CharField(
                        choices=[
                            ("mobile", "Mobile"),
                            ("desktop", "Desktop"),
                            ("tablet", "Tablet"),
                            ("unknown", "Unknown"),
                        ],
                        default="unknown",
                        max_length=20,
                    ),
                ),
                (
                    "device_brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "device_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "operating_system",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "browser_name",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "browser_version",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("user_agent", models.TextField(blank=True, null=True)),
                (
                    "camera_brand",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "camera_model",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
            ],
            options={
                "db_table": "images",
                "ordering": ["-uploaded_at"],
                "indexes": [
                    models.Index(
                        fields=["uploaded_at"], name="images_uploade_2baac5_idx"
                    ),
                    models.Index(
                        fields=["captured_at"], name="images_capture_c8768d_idx"
                    ),
                    models.Index(
                        fields=["device_type"], name="images_device__6f0608_idx"
                    ),
                ],
            },
        ),
    ]
