# Generated by Django 4.2.18 on 2026-03-23 17:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file_name",
            field=models.CharField(blank=True, editable=False, max_length=255),
        ),
    ]
