# Generated by Django 4.2.18 on 2026-03-23 17:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0002_alter_image_file_name"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="file_extension",
            field=models.CharField(blank=True, editable=False, max_length=10),
        ),
    ]
