# Generated by Django 4.2.18 on 2026-03-23 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0003_image_file_extension"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="user_agent",
        ),
        migrations.AlterField(
            model_name="image",
            name="browser_name",
            field=models.CharField(
                blank=True,
                help_text="Nombre del navegador desde donde se envio la imagen.",
                max_length=100,
                null=True,
                verbose_name="Navegador",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="browser_version",
            field=models.CharField(
                blank=True,
                help_text="Version del navegador del cliente.",
                max_length=100,
                null=True,
                verbose_name="Version del navegador",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="camera_brand",
            field=models.CharField(
                blank=True,
                help_text="Marca de la camara, si esta disponible.",
                max_length=100,
                null=True,
                verbose_name="Marca de camara",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="camera_model",
            field=models.CharField(
                blank=True,
                help_text="Modelo de la camara, si esta disponible.",
                max_length=100,
                null=True,
                verbose_name="Modelo de camara",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="captured_at",
            field=models.DateTimeField(
                blank=True,
                help_text="Fecha y hora en que se capturo la imagen.",
                null=True,
                verbose_name="Fecha de captura",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="device_brand",
            field=models.CharField(
                blank=True,
                help_text="Marca del dispositivo (ejemplo: Samsung, Apple).",
                max_length=100,
                null=True,
                verbose_name="Marca del dispositivo",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="device_model",
            field=models.CharField(
                blank=True,
                help_text="Modelo del dispositivo que capturo/subio la imagen.",
                max_length=100,
                null=True,
                verbose_name="Modelo del dispositivo",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="device_type",
            field=models.CharField(
                choices=[
                    ("mobile", "Mobile"),
                    ("desktop", "Desktop"),
                    ("tablet", "Tablet"),
                    ("unknown", "Unknown"),
                ],
                default="unknown",
                help_text="Tipo de dispositivo que genero la imagen.",
                max_length=20,
                verbose_name="Tipo de dispositivo",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                help_text="Imagen a almacenar en el sistema.",
                upload_to="images/%Y/%m/%d/",
                verbose_name="Archivo",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file_extension",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Extension del archivo (ejemplo: .jpg, .png), calculada automaticamente.",
                max_length=10,
                verbose_name="Extension",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="file_name",
            field=models.CharField(
                blank=True,
                editable=False,
                help_text="Nombre original del archivo, calculado automaticamente.",
                max_length=255,
                verbose_name="Nombre del archivo",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="ip_address",
            field=models.GenericIPAddressField(
                blank=True,
                help_text="IP desde donde se envio la imagen.",
                null=True,
                verbose_name="Direccion IP",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="operating_system",
            field=models.CharField(
                blank=True,
                help_text="Sistema operativo del dispositivo.",
                max_length=100,
                null=True,
                verbose_name="Sistema operativo",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="uploaded_at",
            field=models.DateTimeField(
                auto_now_add=True,
                help_text="Fecha y hora en que el archivo fue subido.",
                verbose_name="Fecha de subida",
            ),
        ),
    ]
