# Generated by Django 4.2.18 on 2026-03-23 18:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0005_image_user"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                help_text="Imagen a almacenar en el sistema.",
                upload_to="imagenes/images/%Y/%m/%d/",
                verbose_name="Archivo",
            ),
        ),
    ]
