# Generated by Django 4.2.18 on 2026-03-23 18:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("image", "0006_alter_image_file"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="file",
            field=models.ImageField(
                help_text="Imagen a almacenar en el sistema.",
                upload_to="images/%Y/%m/%d/",
                verbose_name="Archivo",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="user",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario propietario que creo este archivo.",
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                related_name="images",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Usuario",
            ),
        ),
    ]
