# Generated by Django 5.2.3 on 2026-03-24 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0007_alter_image_file_alter_image_user"),
    ]

    operations = [
        migrations.AddField(
            model_name="image",
            name="image_min_score",
            field=models.FloatField(
                blank=True,
                editable=False,
                help_text="Umbral minimo de score requerido para validar la imagen.",
                null=True,
                verbose_name="Score minimo de imagen",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="image_score",
            field=models.FloatField(
                blank=True,
                editable=False,
                help_text="Score obtenido por el validador de imagen.",
                null=True,
                verbose_name="Score de imagen",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="image_validation_message",
            field=models.TextField(
                blank=True,
                default="",
                editable=False,
                help_text="Mensaje de salida de validacion del modelo ML.",
                verbose_name="Mensaje de validacion",
            ),
        ),
        migrations.AddField(
            model_name="image",
            name="validation_model_type",
            field=models.CharField(
                blank=True,
                default="",
                editable=False,
                help_text="Modelo(s) ML usados para validar la imagen.",
                max_length=255,
                verbose_name="Modelo de validacion",
            ),
        ),
    ]
