# Generated by Django 5.2.3 on 2026-03-24 15:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0008_image_image_min_score_image_image_score_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="image",
            name="image_validation_message",
        ),
        migrations.AddField(
            model_name="image",
            name="image_label_target",
            field=models.IntegerField(
                blank=True,
                editable=False,
                help_text="ID de la etiqueta objetivo del modelo (ejemplo: bird).",
                null=True,
                verbose_name="ID de etiqueta objetivo",
            ),
        ),
    ]
