# Generated by Django 5.2.3 on 2026-03-28 00:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("image", "0010_image_reward_fields"),
    ]

    operations = [
        migrations.AlterField(
            model_name="image",
            name="image_label_target",
            field=models.IntegerField(
                blank=True,
                help_text="ID de la etiqueta objetivo del modelo (ejemplo: bird).",
                null=True,
                verbose_name="ID de etiqueta objetivo",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_min_score",
            field=models.FloatField(
                blank=True,
                help_text="Umbral minimo de score requerido para validar la imagen.",
                null=True,
                verbose_name="Score minimo de imagen",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="image_score",
            field=models.FloatField(
                blank=True,
                help_text="Score obtenido por el validador de imagen.",
                null=True,
                verbose_name="Score de imagen",
            ),
        ),
        migrations.AlterField(
            model_name="image",
            name="validation_model_type",
            field=models.CharField(
                blank=True,
                default="",
                help_text="Modelo(s) ML usados para validar la imagen.",
                max_length=255,
                verbose_name="Modelo de validacion",
            ),
        ),
    ]
