# Generated by Django 4.2.18 on 2026-03-23 19:03

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import model_utils.fields
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "created",
                    model_utils.fields.AutoCreatedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="created",
                    ),
                ),
                (
                    "modified",
                    model_utils.fields.AutoLastModifiedField(
                        default=django.utils.timezone.now,
                        editable=False,
                        verbose_name="modified",
                    ),
                ),
                (
                    "id",
                    model_utils.fields.UUIDField(
                        default=uuid.uuid4,
                        editable=False,
                        primary_key=True,
                        serialize=False,
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        help_text="Nombre de la etiqueta.",
                        max_length=100,
                        verbose_name="Nombre",
                    ),
                ),
                (
                    "parent",
                    models.ForeignKey(
                        blank=True,
                        help_text="Etiqueta padre para construir jerarquias.",
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="children",
                        to="tag.tag",
                        verbose_name="Etiqueta padre",
                    ),
                ),
            ],
            options={
                "db_table": "tags",
                "ordering": ["name"],
                "indexes": [
                    models.Index(fields=["name"], name="tags_name_38920e_idx"),
                    models.Index(fields=["parent"], name="tags_parent__7fcc39_idx"),
                ],
            },
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", False)),
                fields=("parent", "name"),
                name="uq_tags_parent_name_not_null",
            ),
        ),
        migrations.AddConstraint(
            model_name="tag",
            constraint=models.UniqueConstraint(
                condition=models.Q(("parent__isnull", True)),
                fields=("name",),
                name="uq_tags_name_root",
            ),
        ),
    ]
